import { NextRequest, NextResponse } from 'next/server'
import connectDB from '@/lib/mongodb'
import { Member } from '@/models/Member'
import { MonthlyWinner } from '@/models/MonthlyWinner'

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
]

// POST - Declare winner for a specific month (or auto-declare for previous month)
export async function POST(request: NextRequest) {
  try {
    await connectDB()
    
    const body = await request.json()
    let { month, year, auto } = body
    
    // If auto mode, declare for previous month
    if (auto) {
      const now = new Date()
      const prevMonth = now.getMonth() === 0 ? 11 : now.getMonth() - 1
      month = MONTHS[prevMonth]
      year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear()
    }
    
    if (!month || !year) {
      return NextResponse.json(
        { success: false, error: 'Month and year are required' },
        { status: 400 }
      )
    }
    
    // Check if winner already declared for this month
    const existingWinner = await MonthlyWinner.findOne({ month, year })
    if (existingWinner) {
      return NextResponse.json(
        { success: false, error: `Winner already declared for ${month} ${year}` },
        { status: 400 }
      )
    }
    
    // Get top members by points
    const topMembers = await Member.find({ isActive: { $ne: false } })
      .sort({ points: -1 })
      .limit(10)
      .lean()
    
    if (topMembers.length === 0) {
      return NextResponse.json(
        { success: false, error: 'No members found to declare winner' },
        { status: 400 }
      )
    }
    
    const winner = topMembers[0] as any
    
    // Create monthly winner record
    const monthlyWinner = await MonthlyWinner.create({
      month,
      year,
      winner: {
        name: winner.name,
        memberId: winner._id.toString(),
        points: winner.points || 0,
        eventsAttended: winner.eventsAttended || 0,
        contributions: winner.contributions || 0,
      },
      topThree: topMembers.slice(0, 3).map((m: any, index) => ({
        rank: index + 1,
        name: m.name,
        memberId: m._id.toString(),
        points: m.points || 0,
      })),
      declaredAt: new Date(),
      isAutoGenerated: !!auto,
    })
    
    return NextResponse.json({
      success: true,
      data: monthlyWinner,
      message: `Winner declared for ${month} ${year}: ${winner.name}`,
    })
    
  } catch (error: any) {
    console.error('Error declaring winner:', error)
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    )
  }
}

// GET - Check if winner needs to be declared (for cron job or admin reminder)
export async function GET(request: NextRequest) {
  try {
    await connectDB()
    
    const now = new Date()
    const prevMonth = now.getMonth() === 0 ? 11 : now.getMonth() - 1
    const month = MONTHS[prevMonth]
    const year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear()
    
    // Check if winner already declared for previous month
    const existingWinner = await MonthlyWinner.findOne({ month, year })
    
    if (existingWinner) {
      return NextResponse.json({
        success: true,
        needsDeclaration: false,
        message: `Winner already declared for ${month} ${year}`,
        winner: existingWinner,
      })
    }
    
    // Get current leader
    const topMember = await Member.findOne({ isActive: { $ne: false } })
      .sort({ points: -1 })
      .lean() as any
    
    return NextResponse.json({
      success: true,
      needsDeclaration: true,
      month,
      year,
      suggestedWinner: topMember ? {
        name: topMember.name,
        points: topMember.points,
        memberId: topMember._id.toString(),
      } : null,
    })
    
  } catch (error: any) {
    console.error('Error checking winner status:', error)
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    )
  }
}
