import mongoose, { Schema, model, models } from 'mongoose'

export interface ILeaderboardEntry {
  rank: number
  name: string
  memberId: string
  points: number
}

export interface IMonthlyWinner {
  _id?: string
  month: string
  year: number
  winner: {
    name: string
    memberId: string
    points: number
    eventsAttended: number
    contributions: number
  }
  topThree: ILeaderboardEntry[]
  declaredAt?: Date
  isAutoGenerated?: boolean
}

const LeaderboardEntrySchema = new Schema<ILeaderboardEntry>({
  rank: { type: Number, required: true },
  name: { type: String, required: true },
  memberId: { type: String, required: true },
  points: { type: Number, required: true },
}, { _id: false })

const MonthlyWinnerSchema = new Schema<IMonthlyWinner>({
  month: { type: String, required: true },
  year: { type: Number, required: true },
  winner: {
    name: { type: String, required: true },
    memberId: { type: String, required: true },
    points: { type: Number, required: true },
    eventsAttended: { type: Number, required: true },
    contributions: { type: Number, required: true },
  },
  topThree: [LeaderboardEntrySchema],
  declaredAt: { type: Date, default: Date.now },
  isAutoGenerated: { type: Boolean, default: false },
}, {
  timestamps: true,
})

MonthlyWinnerSchema.index({ year: -1, month: -1 })

export const MonthlyWinner = models.MonthlyWinner || model<IMonthlyWinner>('MonthlyWinner', MonthlyWinnerSchema)
